name: odoo18

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - odoo-18-db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:18.0
    restart: always
    depends_on:
      - db
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    ports:
      - "8070:8069"
    volumes:
      - odoo-18-web-data:/var/lib/odoo
      - ./custom_addons:/mnt/extra-addons

volumes:
  odoo-18-db-data:
  odoo-18-web-data:
