name: odoo19

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - odoo-19-db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:19.0
    restart: always
    depends_on:
      - db
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    ports:
      - "8071:8069"
    volumes:
      - odoo-19-web-data:/var/lib/odoo
      - ./custom_addons:/mnt/extra-addons

volumes:
  odoo-19-db-data:
  odoo-19-web-data:
